version: '3.9'

services:
  boilerplate-mysql:
    container_name: boilerplate-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boilerplate
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '53306:3306'
    healthcheck:
      test: mysqladmin ping --host=localhost --port=53306 --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 30s
      start_period: 10s
    volumes:
      - boilerplate-mysql-volume:/var/lib/mysql
    networks:
      - boilerplate-network
  boilerplate-redis:
    container_name: boilerplate-redis
    image: redis:7
    ports:
      - '56379:6379'
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 30s
      start_period: 10s
    volumes:
      - boilerplate-redis-volume:/data
    networks:
      - boilerplate-network

volumes:
  boilerplate-mysql-volume:
  boilerplate-redis-volume:

networks:
  boilerplate-network:
    name: boilerplate-network
    driver: bridge
