FROM node:16.19.1 AS base
ENV NODE_ENV=production
WORKDIR /opt/project
COPY ./package.aws-prisma.json ./package.json
RUN npm install
RUN mkdir -p ./prisma
COPY ./prisma/schema.prisma ./prisma
COPY ./tsconfig.json ./
RUN ["npx", "prisma", "generate"]

FROM base as migration
ENV NODE_ENV=production
RUN mkdir -p ./prisma/migrations
COPY ./prisma/migrations ./prisma/migrations
CMD ["npx", "prisma", "migrate", "deploy"]

FROM base AS seed
ENV NODE_ENV=production
COPY ./prisma/seed.ts ./prisma
CMD ["npx", "prisma", "db", "seed"]
