FROM node:14.19.1 AS builder
ENV NODE_ENV=development
WORKDIR /opt/project
COPY ./package*.json ./
RUN npm i
COPY . .
RUN npm run build

FROM node:14.19.1
ENV NODE_ENV=development
WORKDIR /opt/project
COPY ./package*.json ./
RUN npm i
COPY . .
# COPY --from=builder /opt/project/dist ./dist
# COPY --from=builder /opt/project/node_modules/.prisma/client ./node_modules/.prisma/client

EXPOSE 23000

# CMD [ "node", "./dist/src/main" ]
CMD [ "npm", "run", "start:aws" ]
