import { CircularProgress } from '@mui/material';
import { AppErrorBoundary } from 'components/common/AppErrorBoundary';
import { SEO } from 'components/common/SEO';
import RecoilStateDebugButton from 'components/dev/RecoilStateDebugBtn';
import { Test } from 'components/dev/Test';
import { useDialog } from 'global-states/dialogs.state';
import { useSetAppSnackbar } from 'global-states/snackbar.state';
import type { NextPage } from 'next';
import { Suspense } from 'react';
import { isDevelopment } from 'utils/env';
import { GoogleIdentity } from '../components/common/GoogleIdentity';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { showDialog } = useDialog();
  const setAppSnackbar = useSetAppSnackbar();

  const handleOpen = () => {
    showDialog({
      title: 'title1',
      contentText: 'contentText1',
      closeText: 'cancel',
      confirmText: 'OK',
      onConfirm: () => {
        alert('onConfirm');
      },
    });
    setAppSnackbar({
      severity: 'error',
      message: 'エラーです',
    });
  };

  return (
    <div className={styles.container}>
      <SEO pageTitle={`Create Next App`} pageDescription={`Generated by create next app`}>
        <link rel="icon" href="/favicon.ico" />
      </SEO>

      <main className={styles.main}>
        <AppErrorBoundary>
          <Suspense fallback={<CircularProgress />}>
            <Test />
          </Suspense>
        </AppErrorBoundary>
        <GoogleIdentity buttonType="LOGIN" />
        {/* <GoogleIdentity buttonType="REGISTER" /> */}
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <p>
            <button type="button" onClick={handleOpen}>
              open
            </button>
          </p>
        </div>
        {isDevelopment() && <RecoilStateDebugButton />}
      </main>
    </div>
  );
};

export default Home;
