import { CircularProgress } from '@mui/material';
import { AppErrorBoundary } from 'components/common/AppErrorBoundary';
import RecoilStateDebugButton from 'components/dev/RecoilStateDebugBtn';
import { Test } from 'components/dev/Test';
import { useDialog } from 'global-states/dialogs.state';
import type { NextPage } from 'next';
import { Suspense } from 'react';
import GoogleIdentity, { GI_BUTTON_TYPE } from '../components/common/GoogleIdentity';
import SEO from '../components/common/SEO';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { showDialog } = useDialog();

  const handleOpen = () => {
    showDialog({
      title: 'title1',
      contentText: 'contentText1',
      closeText: 'cancel',
      confirmText: 'OK',
      onConfirm: () => {
        alert('onConfirm');
      },
    });
  };

  return (
    <div className={styles.container}>
      <SEO pageTitle={`Create Next App`} pageDescription={`Generated by create next app`}>
        <link rel="icon" href="/favicon.ico" />
      </SEO>

      <main className={styles.main}>
        <AppErrorBoundary>
          <Suspense fallback={<CircularProgress />}>
            <Test />
          </Suspense>
        </AppErrorBoundary>
        <GoogleIdentity buttonType={GI_BUTTON_TYPE.LOGIN} />
        {/* <GoogleIdentity buttonType={GI_BUTTON_TYPE.REGISTER} /> */}
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <p>
            <button type="button" onClick={handleOpen}>
              open
            </button>
          </p>
        </div>
        {process.env.NODE_ENV === 'development' && <RecoilStateDebugButton />}
      </main>
    </div>
  );
};

export default Home;
